appium.server.url=http://127.0.0.1:4723/

platform.name=Android
device.name=Android Emulator
automation.name=UiAutomator2
platform.version=

# Option 1: use APK path
app.path=

# Option 2: use package/activity when app is already installed
app.package=com.snapwork.kotak
app.activity=com.snapwork.kotak.MainActivity

no.reset=true
full.reset=false
new.command.timeout=120

# Registration smoke test data
registration.crn.mask=9951
registration.netbanking.password=Quality@123
registration.otp=123456
registration.mpin=020202
registration.manual.wait.seconds=30
